title: Akbar
description: A bookmarklet that simulates various types user experiences.  It is an education tool that will hopefully education people about web accessibility.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
