title: Visual Impairment Simulator
description: A bookmarklet that simulates various types of users with visual disabilities. 
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
